#!/usr/bin/env bash
set -euo pipefail
forge_bin="${1:-target/release/ayeque-forge}"
forge_bin="$(readlink -f "$forge_bin")"
smoke_root="$(mktemp -d)"
trap 'rm -rf "$smoke_root"' EXIT
workspace="$smoke_root/workspace"
data="$smoke_root/data"
config="$smoke_root/config"
mkdir -p "$workspace" "$config"
XDG_DATA_HOME="$data" XDG_CONFIG_HOME="$config" HOME="$smoke_root" "$forge_bin" init "$workspace"
XDG_DATA_HOME="$data" XDG_CONFIG_HOME="$config" HOME="$smoke_root" "$forge_bin" init "$workspace"
project="$data/ayeque-forge/projects/workspace"
test -f "$project/FORGE.toml"
test -f "$project/FORGE.lock"
test ! -e "$workspace/FORGE.toml"
test ! -e "$workspace/FORGE.lock"
paths="$(cd "$workspace" && XDG_DATA_HOME="$data" XDG_CONFIG_HOME="$config" HOME="$smoke_root" "$forge_bin" paths)"
grep -F "project" <<< "$paths" | grep -F "$project"
grep -F "manifest" <<< "$paths" | grep -F "$project/FORGE.toml"
override="$smoke_root/override"
XDG_DATA_HOME="$data" XDG_CONFIG_HOME="$config" HOME="$smoke_root" "$forge_bin" config storage-root "$override"
test -d "$override/git"
test -d "$override/projects"
echo "ayeque-forge release live smoke passed"
